[package]
authors = ["Daniel <knightpp@pm.me>"]
description = "Automatically enter giveaways for steamgifts.com"
edition = "2018"
license = "MIT|Apache-2.0"
name = "steamgiftsbot"
readme = "README.md"
version = "0.5.0"
[[bin]]
name = "steamgiftsbot"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
console = "0.15"
humantime = "2.1"
scraper = "0.12"
thiserror = "1.0"
tide = "0.16"
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.10", features = ["attributes"] }
simplelog = "0.10"
log = "0.4"

[dependencies.ureq]
features = ["json"]
version = "2.2"

[lib]
path = "src/lib.rs"

[profile]
[profile.release]
codegen-units = 1
lto = true

#opt-level = 3
