[package]
name = "steamgiftsbot"
version = "0.2.3"
authors = ["Daniel <knightpp@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "1.3", features = ["json"] }
scraper = "0.12"
simple-error = "0.2"
console = "0.12"
clap = "2.33"
pbr = "1.0"

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = "s"
