[package]
name = "steamgiftsbot"
version = "0.3.0"
authors = ["Daniel <knightpp@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "1.3", features = ["json"] }
scraper = "0.12"
console = "0.12"
pbr = "1.0"
argh = "0.1"
anyhow = "1.0"    # for binary
thiserror = "1.0" # for lib

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
