[package]
name = "steamgiftsbot"
version = "0.4.0"
authors = ["Daniel <knightpp@pm.me>"]
edition = "2018"
description = "Automatically enter giveaways for steamgifts.com"
license = "MIT|Apache-2.0"
readme = "README.md"
#resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.2", features = ["json"] }
scraper = "0.12"
console = "0.14"
pbr = "1.0"
argh = "0.1"
anyhow = "1.0"
thiserror = "1.0"
oorandom = "11.1"
humantime = "2.1"

[profile.release]
lto = true
codegen-units = 1
#opt-level = 3
