[package]
name = "steamgiftsbot"
version = "0.1.1"
authors = ["Daniel <knightpp@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "0.11", features = ["json"] }
scraper = "0.11"
simple-error = "0.2"
console = "0.9"
clap = "2.33"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
