name: Rust publish

on:
  push:
    tags: 
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build release
      run: cargo build --release --verbose
    - name: Upload release
      uses: yakuhzi/action-release@v1
      with:
          file: ./target/release/steamgiftsbot.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
